# [enum_const]
# # allow_static_const = true
# # # associated_constants_in_body: true
# "BLOCKSIZE" = { value = 64 }
# "SHA256LENGTH" = { value = 8 }
# "SM_H256" = { values = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19] }
